---
name: MooseX-Struct
version: 0.05
author:
  - 'Jarrod Overson <jsoverson@gmail.com>'
abstract: Class::Struct for Moose
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Moose: 0
  Sub::Install: 0
build_requires:
  Test::More: 0
provides:
  MooseX::Struct:
    file: lib/MooseX/Struct.pm
    version: 0.05
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
